basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is a sample Echo API with Swagger docs.
  title: Echo Swagger Example API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Простой эндпоинт для примера
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Возвращает "Hello, World!"
      tags:
      - example
swagger: "2.0"
