definitions:
  models.Pet:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Fluffy
        type: string
      type:
        example: cat
        type: string
    type: object
info:
  contact: {}
  title: My Echo API
  version: "1.0"
paths:
  /api/pets/{id}:
    get:
      description: Get pet details
      parameters:
      - description: Pet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Pet'
      summary: Get pet by ID
      tags:
      - pets
swagger: "2.0"
